### ISSUE TITLE
The unavailable library 'dart:html' is imported through these packages:

### ISSUE THREAD

**Issue by Yoda-Man** [moluopro/webview_all#7]
/C:/Users/trust/AppData/Local/Pub/Cache/hosted/pub.dev/webview_flutter_web-0.2.2+3/lib/src/http_request_factory.dart:5:8: Error: Dart library 'dart:html' is not available on this platform.
import 'dart:html';
       ^
Context: The unavailable library 'dart:html' is imported through these packages:

    package:altar => package:webview_all => package:webview_flutter_web => dart:html

Detailed import paths for (some of) the these imports:

    package:altar/main.dart => package:altar/model/startupdata.dart => package:altar/widgets/information.dart => package:webview_all/webview_all.dart => package:webview_all/src/webview/webview.dart => package:webview_all/src/webview/webview_web.dart => package:webview_flutter_web/webview_flutter_web.dart => package:webview_flutter_web/src/http_request_factory.dart => dart:html
    package:altar/main.dart => package:altar/model/startupdata.dart => package:altar/widgets/information.dart => package:webview_all/webview_all.dart => package:webview_all/src/webview/webview.dart => package:webview_all/src/webview/webview_web.dart => package:webview_flutter_web/webview_flutter_web.dart => package:webview_flutter_web/src/web_webview_controller.dart => dart:html
    package:altar/main.dart => package:altar/model/startupdata.dart => package:altar/widgets/information.dart => package:webview_all/webview_all.dart => package:webview_all/src/webview/webview.dart => package:webview_all/src/webview/webview_web.dart => package:webview_flutter_web/webview_flutter_web.dart => package:webview_flutter_web/src/web_webview_controller.dart => package:webview_flutter_web/src/http_request_factory.dart => dart:html
    package:altar/main.dart => package:altar/model/startupdata.dart => package:altar/widgets/information.dart => package:webview_all/webview_all.dart => package:webview_all/src/webview/webview.dart => package:webview_all/src/webview/webview_web.dart => package:webview_flutter_web/webview_flutter_web.dart => package:webview_flutter_web/src/web_webview_platform.dart => package:webview_flutter_web/src/web_webview_controller.dart => dart:html
    package:altar/main.dart => package:altar/model/startupdata.dart => package:altar/widgets/information.dart => package:webview_all/webview_all.dart => package:webview_all/src/webview/webview.dart => package:webview_all/src/webview/webview_web.dart => package:webview_flutter_web/webview_flutter_web.dart => package:webview_flutter_web/src/web_webview_platform.dart => package:webview_flutter_web/src/web_webview_controller.dart => package:webview_flutter_web/src/http_request_factory.dart => dart:html
    package:altar/main.dart => package:altar/pages/audio_page.dart => package:altar/widgets/information.dart => package:webview_all/webview_all.dart => package:webview_all/src/webview/webview.dart => package:webview_all/src/webview/webview_web.dart => package:webview_flutter_web/webview_flutter_web.dart => package:webview_flutter_web/src/http_request_factory.dart => dart:html
    package:altar/main.dart => package:altar/pages/audio_page.dart => package:altar/widgets/information.dart => package:webview_all/webview_all.dart => package:webview_all/src/webview/webview.dart => package:webview_all/src/webview/webview_web.dart => package:webview_flutter_web/webview_flutter_web.dart => package:webview_flutter_web/src/web_webview_controller.dart => dart:html
    package:altar/main.dart => package:altar/pages/audio_page.dart => package:altar/widgets/information.dart => package:webview_all/webview_all.dart => package:webview_all/src/webview/webview.dart => package:webview_all/src/webview/webview_web.dart => package:webview_flutter_web/webview_flutter_web.dart => package:webview_flutter_web/src/web_webview_controller.dart => package:webview_flutter_web/src/http_request_factory.dart => dart:html
    package:altar/main.dart => package:altar/pages/audio_page.dart => package:altar/widgets/information.dart => package:webview_all/webview_all.dart => package:webview_all/src/webview/webview.dart => package:webview_all/src/webview/webview_web.dart => package:webview_flutter_web/webview_flutter_web.dart => package:webview_flutter_web/src/web_webview_platform.dart => package:webview_flutter_web/src/web_webview_controller.dart => dart:html
    package:altar/main.dart => package:altar/pages/audio_page.dart => package:altar/widgets/information.dart => package:webview_all/webview_all.dart => package:webview_all/src/webview/webview.dart => package:webview_all/src/webview/webview_web.dart => package:webview_flutter_web/webview_flutter_web.dart => package:webview_flutter_web/src/web_webview_platform.dart => package:webview_flutter_web/src/web_webview_controller.dart => package:webview_flutter_web/src/http_request_factory.dart => dart:html
    package:altar/main.dart => package:altar/pages/audio_page.dart => package:altar/widgets/main_drawer.dart => package:altar/pages/login_page.dart => package:altar/model/startupdata.dart => package:altar/widgets/information.dart => package:webview_all/webview_all.dart => package:webview_all/src/webview/webview.dart => package:webview_all/src/webview/webview_web.dart => package:webview_flutter_web/webview_flutter_web.dart => package:webview_flutter_web/src/http_request_factory.dart => dart:html
    package:altar/main.dart => package:altar/pages/audio_page.dart => package:altar/widgets/main_drawer.dart => package:altar/pages/login_page.dart => package:altar/model/startupdata.dart => package:altar/widgets/information.dart => package:webview_all/webview_all.dart => package:webview_all/src/webview/webview.dart => package:webview_all/src/webview/webview_web.dart => package:webview_flutter_web/webview_flutter_web.dart => package:webview_flutter_web/src/web_webview_controller.dart => dart:html
    package:altar/main.dart => package:altar/pages/audio_page.dart => package:altar/widgets/main_drawer.dart => package:altar/pages/login_page.dart => package:altar/model/startupdata.dart => package:altar/widgets/information.dart => package:webview_all/webview_all.dart => package:webview_all/src/webview/webview.dart => package:webview_all/src/webview/webview_web.dart => package:webview_flutter_web/webview_flutter_web.dart => package:webview_flutter_web/src/web_webview_controller.dart => package:webview_flutter_web/src/http_request_factory.dart => dart:html
    package:altar/main.dart => package:altar/pages/audio_page.dart => package:altar/widgets/main_drawer.dart => package:altar/pages/login_page.dart => package:altar/model/startupdata.dart => package:altar/widgets/information.dart => package:webview_all/webview_all.dart => package:webview_all/src/webview/webview.dart => package:webview_all/src/webview/webview_web.dart => package:webview_flutter_web/webview_flutter_web.dart => package:webview_flutter_web/src/web_webview_platform.dart => package:webview_flutter_web/src/web_webview_controller.dart => dart:html
    package:altar/main.dart => package:altar/pages/audio_page.dart => package:altar/widgets/main_drawer.dart => package:altar/pages/login_page.dart => package:altar/model/startupdata.dart => package:altar/widgets/information.dart => package:webview_all/webview_all.dart => package:webview_all/src/webview/webview.dart => package:webview_all/src/webview/webview_web.dart => package:webview_flutter_web/webview_flutter_web.dart => package:webview_flutter_web/src/web_webview_platform.dart => package:webview_flutter_web/src/web_webview_controller.dart => package:webview_flutter_web/src/http_request_factory.dart => dart:html
    package:altar/main.dart => package:altar/pages/audio_page.dart => package:altar/widgets/main_drawer.dart => package:altar/pages/login_page.dart => package:altar/model/firebase.dart => package:altar/model/startupdata.dart => package:altar/widgets/information.dart => package:webview_all/webview_all.dart => package:webview_all/src/webview/webview.dart => package:webview_all/src/webview/webview_web.dart => package:webview_flutter_web/webview_flutter_web.dart => package:webview_flutter_web/src/http_request_factory.dart => dart:html
    package:altar/main.dart => package:altar/pages/audio_page.dart => package:altar/widgets/main_drawer.dart => package:altar/pages/login_page.dart => package:altar/model/firebase.dart => package:altar/model/startupdata.dart => package:altar/widgets/information.dart => package:webview_all/webview_all.dart => package:webview_all/src/webview/webview.dart => package:webview_all/src/webview/webview_web.dart => package:webview_flutter_web/webview_flutter_web.dart => package:webview_flutter_web/src/web_webview_controller.dart => dart:html
    package:altar/main.dart => package:altar/pages/audio_page.dart => package:altar/widgets/main_drawer.dart => package:altar/pages/login_page.dart => package:altar/model/firebase.dart => package:altar/model/startupdata.dart => package:altar/widgets/information.dart => package:webview_all/webview_all.dart => package:webview_all/src/webview/webview.dart => package:webview_all/src/webview/webview_web.dart => package:webview_flutter_web/webview_flutter_web.dart => package:webview_flutter_web/src/web_webview_controller.dart => package:webview_flutter_web/src/http_request_factory.dart => dart:html
    package:altar/main.dart => package:altar/pages/audio_page.dart => package:altar/widgets/main_drawer.dart => package:altar/pages/login_page.dart => package:altar/model/firebase.dart => package:altar/model/startupdata.dart => package:altar/widgets/information.dart => package:webview_all/webview_all.dart => package:webview_all/src/webview/webview.dart => package:webview_all/src/webview/webview_web.dart => package:webview_flutter_web/webview_flutter_web.dart => package:webview_flutter_web/src/web_webview_platform.dart => package:webview_flutter_web/src/web_webview_controller.dart => dart:html
    package:altar/main.dart => package:altar/pages/audio_page.dart => package:altar/widgets/main_drawer.dart => package:altar/pages/login_page.dart => package:altar/model/firebase.dart => package:altar/model/startupdata.dart => package:altar/widgets/information.dart => package:webview_all/webview_all.dart => package:webview_all/src/webview/webview.dart => package:webview_all/src/webview/webview_web.dart => package:webview_flutter_web/webview_flutter_web.dart => package:webview_flutter_web/src/web_webview_platform.dart => package:webview_flutter_web/src/web_webview_controller.dart => package:webview_flutter_web/src/http_request_factory.dart => dart:html
    package:altar/main.dart => package:altar/pages/audio_page.dart => package:altar/widgets/main_drawer.dart => package:altar/pages/login_page.dart => package:altar/model/firebase.dart => package:altar/pages/home_page.dart => package:altar/widgets/current_track.dart => package:altar/model/startupdata.dart => package:altar/widgets/information.dart => package:webview_all/webview_all.dart => package:webview_all/src/webview/webview.dart => package:webview_all/src/webview/webview_web.dart => package:webview_flutter_web/webview_flutter_web.dart => package:webview_flutter_web/src/http_request_factory.dart => dart:html
    ...

/C:/Users/trust/AppData/Local/Pub/Cache/hosted/pub.dev/webview_flutter_web-0.2.2+3/lib/src/web_webview_controller.dart:7:8: Error: Dart library 'dart:ui_web' is not available on this platform.
import 'dart:ui_web' as ui_web;
       ^
Context: The unavailable library 'dart:ui_web' is imported through these packages:

    package:altar => package:webview_all => package:webview_flutter_web => dart:ui_web
    package:altar => package:webview_all => package:webview_flutter_web => package:flutter_web_plugins => dart:ui_web

Detailed import paths for (some of) the these imports:

    package:altar/main.dart => package:altar/model/startupdata.dart => package:altar/widgets/information.dart => package:webview_all/webview_all.dart => package:webview_all/src/webview/webview.dart => package:webview_all/src/webview/webview_web.dart => package:webview_flutter_web/webview_flutter_web.dart => package:webview_flutter_web/src/web_webview_controller.dart => dart:ui_web
    package:altar/main.dart => package:altar/model/startupdata.dart => package:altar/widgets/information.dart => package:webview_all/webview_all.dart => package:webview_all/src/webview/webview.dart => package:webview_all/src/webview/webview_web.dart => package:webview_flutter_web/webview_flutter_web.dart => package:webview_flutter_web/src/web_webview_platform.dart => package:flutter_web_plugins/flutter_web_plugins.dart => package:flutter_web_plugins/src/navigation/url_strategy.dart => dart:ui_web
    package:altar/main.dart => package:altar/model/startupdata.dart => package:altar/widgets/information.dart => package:webview_all/webview_all.dart => package:webview_all/src/webview/webview.dart => package:webview_all/src/webview/webview_web.dart => package:webview_flutter_web/webview_flutter_web.dart => package:webview_flutter_web/src/web_webview_platform.dart => package:flutter_web_plugins/flutter_web_plugins.dart => package:flutter_web_plugins/src/plugin_event_channel.dart => package:flutter_web_plugins/src/plugin_registry.dart => dart:ui_web
    package:altar/main.dart => package:altar/model/startupdata.dart => package:altar/widgets/information.dart => package:webview_all/webview_all.dart => package:webview_all/src/webview/webview.dart => package:webview_all/src/webview/webview_web.dart => package:webview_flutter_web/webview_flutter_web.dart => package:webview_flutter_web/src/web_webview_platform.dart => package:flutter_web_plugins/flutter_web_plugins.dart => package:flutter_web_plugins/src/plugin_registry.dart => dart:ui_web
    package:altar/main.dart => package:altar/model/startupdata.dart => package:altar/widgets/information.dart => package:webview_all/webview_all.dart => package:webview_all/src/webview/webview.dart => package:webview_all/src/webview/webview_web.dart => package:webview_flutter_web/webview_flutter_web.dart => package:webview_flutter_web/src/web_webview_platform.dart => package:webview_flutter_web/src/web_webview_controller.dart => dart:ui_web
    package:altar/main.dart => package:altar/pages/audio_page.dart => package:altar/widgets/information.dart => package:webview_all/webview_all.dart => package:webview_all/src/webview/webview.dart => package:webview_all/src/webview/webview_web.dart => package:webview_flutter_web/webview_flutter_web.dart => package:webview_flutter_web/src/web_webview_controller.dart => dart:ui_web
    package:altar/main.dart => package:altar/pages/audio_page.dart => package:altar/widgets/information.dart => package:webview_all/webview_all.dart => package:webview_all/src/webview/webview.dart => package:webview_all/src/webview/webview_web.dart => package:webview_flutter_web/webview_flutter_web.dart => package:webview_flutter_web/src/web_webview_platform.dart => package:flutter_web_plugins/flutter_web_plugins.dart => package:flutter_web_plugins/src/navigation/url_strategy.dart => dart:ui_web
    package:altar/main.dart => package:altar/pages/audio_page.dart => package:altar/widgets/information.dart => package:webview_all/webview_all.dart => package:webview_all/src/webview/webview.dart => package:webview_all/src/webview/webview_web.dart => package:webview_flutter_web/webview_flutter_web.dart => package:webview_flutter_web/src/web_webview_platform.dart => package:flutter_web_plugins/flutter_web_plugins.dart => package:flutter_web_plugins/src/plugin_event_channel.dart => package:flutter_web_plugins/src/plugin_registry.dart => dart:ui_web
    package:altar/main.dart => package:altar/pages/audio_page.dart => package:altar/widgets/information.dart => package:webview_all/webview_all.dart => package:webview_all/src/webview/webview.dart => package:webview_all/src/webview/webview_web.dart => package:webview_flutter_web/webview_flutter_web.dart => package:webview_flutter_web/src/web_webview_platform.dart => package:flutter_web_plugins/flutter_web_plugins.dart => package:flutter_web_plugins/src/plugin_registry.dart => dart:ui_web
    package:altar/main.dart => package:altar/pages/audio_page.dart => package:altar/widgets/information.dart => package:webview_all/webview_all.dart => package:webview_all/src/webview/webview.dart => package:webview_all/src/webview/webview_web.dart => package:webview_flutter_web/webview_flutter_web.dart => package:webview_flutter_web/src/web_webview_platform.dart => package:webview_flutter_web/src/web_webview_controller.dart => dart:ui_web
    package:altar/main.dart => package:altar/pages/audio_page.dart => package:altar/widgets/main_drawer.dart => package:altar/pages/login_page.dart => package:altar/model/startupdata.dart => package:altar/widgets/information.dart => package:webview_all/webview_all.dart => package:webview_all/src/webview/webview.dart => package:webview_all/src/webview/webview_web.dart => package:webview_flutter_web/webview_flutter_web.dart => package:webview_flutter_web/src/web_webview_controller.dart => dart:ui_web
    package:altar/main.dart => package:altar/pages/audio_page.dart => package:altar/widgets/main_drawer.dart => package:altar/pages/login_page.dart => package:altar/model/startupdata.dart => package:altar/widgets/information.dart => package:webview_all/webview_all.dart => package:webview_all/src/webview/webview.dart => package:webview_all/src/webview/webview_web.dart => package:webview_flutter_web/webview_flutter_web.dart => package:webview_flutter_web/src/web_webview_platform.dart => package:flutter_web_plugins/flutter_web_plugins.dart => package:flutter_web_plugins/src/navigation/url_strategy.dart => dart:ui_web
    package:altar/main.dart => package:altar/pages/audio_page.dart => package:altar/widgets/main_drawer.dart => package:altar/pages/login_page.dart => package:altar/model/startupdata.dart => package:altar/widgets/information.dart => package:webview_all/webview_all.dart => package:webview_all/src/webview/webview.dart => package:webview_all/src/webview/webview_web.dart => package:webview_flutter_web/webview_flutter_web.dart => package:webview_flutter_web/src/web_webview_platform.dart => package:flutter_web_plugins/flutter_web_plugins.dart => package:flutter_web_plugins/src/plugin_event_channel.dart => package:flutter_web_plugins/src/plugin_registry.dart => dart:ui_web
    package:altar/main.dart => package:altar/pages/audio_page.dart => package:altar/widgets/main_drawer.dart => package:altar/pages/login_page.dart => package:altar/model/startupdata.dart => package:altar/widgets/information.dart => package:webview_all/webview_all.dart => package:webview_all/src/webview/webview.dart => package:webview_all/src/webview/webview_web.dart => package:webview_flutter_web/webview_flutter_web.dart => package:webview_flutter_web/src/web_webview_platform.dart => package:flutter_web_plugins/flutter_web_plugins.dart => package:flutter_web_plugins/src/plugin_registry.dart => dart:ui_web
    package:altar/main.dart => package:altar/pages/audio_page.dart => package:altar/widgets/main_drawer.dart => package:altar/pages/login_page.dart => package:altar/model/startupdata.dart => package:altar/widgets/information.dart => package:webview_all/webview_all.dart => package:webview_all/src/webview/webview.dart => package:webview_all/src/webview/webview_web.dart => package:webview_flutter_web/webview_flutter_web.dart => package:webview_flutter_web/src/web_webview_platform.dart => package:webview_flutter_web/src/web_webview_controller.dart => dart:ui_web
    package:altar/main.dart => package:altar/pages/audio_page.dart => package:altar/widgets/main_drawer.dart => package:altar/pages/login_page.dart => package:altar/model/firebase.dart => package:altar/model/startupdata.dart => package:altar/widgets/information.dart => package:webview_all/webview_all.dart => package:webview_all/src/webview/webview.dart => package:webview_all/src/webview/webview_web.dart => package:webview_flutter_web/webview_flutter_web.dart => package:webview_flutter_web/src/web_webview_controller.dart => dart:ui_web
    package:altar/main.dart => package:altar/pages/audio_page.dart => package:altar/widgets/main_drawer.dart => package:altar/pages/login_page.dart => package:altar/model/firebase.dart => package:altar/model/startupdata.dart => package:altar/widgets/information.dart => package:webview_all/webview_all.dart => package:webview_all/src/webview/webview.dart => package:webview_all/src/webview/webview_web.dart => package:webview_flutter_web/webview_flutter_web.dart => package:webview_flutter_web/src/web_webview_platform.dart => package:flutter_web_plugins/flutter_web_plugins.dart => package:flutter_web_plugins/src/navigation/url_strategy.dart => dart:ui_web
    package:altar/main.dart => package:altar/pages/audio_page.dart => package:altar/widgets/main_drawer.dart => package:altar/pages/login_page.dart => package:altar/model/firebase.dart => package:altar/model/startupdata.dart => package:altar/widgets/information.dart => package:webview_all/webview_all.dart => package:webview_all/src/webview/webview.dart => package:webview_all/src/webview/webview_web.dart => package:webview_flutter_web/webview_flutter_web.dart => package:webview_flutter_web/src/web_webview_platform.dart => package:flutter_web_plugins/flutter_web_plugins.dart => package:flutter_web_plugins/src/plugin_event_channel.dart => package:flutter_web_plugins/src/plugin_registry.dart => dart:ui_web
    package:altar/main.dart => package:altar/pages/audio_page.dart => package:altar/widgets/main_drawer.dart => package:altar/pages/login_page.dart => package:altar/model/firebase.dart => package:altar/model/startupdata.dart => package:altar/widgets/information.dart => package:webview_all/webview_all.dart => package:webview_all/src/webview/webview.dart => package:webview_all/src/webview/webview_web.dart => package:webview_flutter_web/webview_flutter_web.dart => package:webview_flutter_web/src/web_webview_platform.dart => package:flutter_web_plugins/flutter_web_plugins.dart => package:flutter_web_plugins/src/plugin_registry.dart => dart:ui_web
    package:altar/main.dart => package:altar/pages/audio_page.dart => package:altar/widgets/main_drawer.dart => package:altar/pages/login_page.dart => package:altar/model/firebase.dart => package:altar/model/startupdata.dart => package:altar/widgets/information.dart => package:webview_all/webview_all.dart => package:webview_all/src/webview/webview.dart => package:webview_all/src/webview/webview_web.dart => package:webview_flutter_web/webview_flutter_web.dart => package:webview_flutter_web/src/web_webview_platform.dart => package:webview_flutter_web/src/web_webview_controller.dart => dart:ui_web
    package:altar/main.dart => package:altar/pages/audio_page.dart => package:altar/widgets/main_drawer.dart => package:altar/pages/login_page.dart => package:altar/model/firebase.dart => package:altar/pages/home_page.dart => package:altar/widgets/current_track.dart => package:altar/model/startupdata.dart => package:altar/widgets/information.dart => package:webview_all/webview_all.dart => package:webview_all/src/webview/webview.dart => package:webview_all/src/webview/webview_web.dart => package:webview_flutter_web/webview_flutter_web.dart => package:webview_flutter_web/src/web_webview_controller.dart => dart:ui_web
    ...

/C:/Users/trust/AppData/Local/Pub/Cache/hosted/pub.dev/webview_flutter_web-0.2.2+3/lib/src/web_webview_controller.dart:6:8: Error: Dart library 'dart:html' is not available on this platform.
import 'dart:html' as html;
       ^
/C:/Flutter/packages/flutter_web_plugins/lib/src/navigation/url_strategy.dart:5:8: Error: Dart library 'dart:ui_web' is not available on this platform.
import 'dart:ui_web' as ui_web;
       ^
/C:/Flutter/packages/flutter_web_plugins/lib/src/navigation/url_strategy.dart:9:1: Error: Dart library 'dart:ui_web' is not available on this platform.
export 'dart:ui_web'
^
/C:/Flutter/packages/flutter_web_plugins/lib/src/plugin_registry.dart:7:8: Error: Dart library 'dart:ui_web' is not available on this platform.    
import 'dart:ui_web' as ui_web;
       ^
/C:/Users/trust/AppData/Local/Pub/Cache/hosted/pub.dev/webview_flutter_web-0.2.2+3/lib/src/http_request_factory.dart:64:10: Error: Type 'HttpRequest' not found.
  Future<HttpRequest> request(String url,
         ^^^^^^^^^^^
/C:/Users/trust/AppData/Local/Pub/Cache/hosted/pub.dev/webview_flutter_web-0.2.2+3/lib/src/http_request_factory.dart:71:21: Error: Type 'ProgressEvent' not found.
      void Function(ProgressEvent e)? onProgress}) {
                    ^^^^^^^^^^^^^
/C:/Users/trust/AppData/Local/Pub/Cache/hosted/pub.dev/webview_flutter_web-0.2.2+3/lib/src/web_webview_controller.dart:41:9: Error: Type 'html.IFrameElement' not found.
  final html.IFrameElement iFrame = html.IFrameElement()
        ^^^^^^^^^^^^^^^^^^
/C:/Flutter/packages/flutter_web_plugins/lib/src/navigation/url_strategy.dart:21:21: Error: Type 'ui_web.UrlStrategy' not found.
void setUrlStrategy(ui_web.UrlStrategy? strategy) {
                    ^^^^^^^^^^^^^^^^^^
/C:/Flutter/packages/flutter_web_plugins/lib/src/navigation/url_strategy.dart:40:31: Error: Type 'ui_web.HashUrlStrategy' not found.
class PathUrlStrategy extends ui_web.HashUrlStrategy {
                              ^^^^^^^^^^^^^^^^^^^^^^
/C:/Flutter/packages/flutter_web_plugins/lib/src/navigation/url_strategy.dart:52:9: Error: Type 'ui_web.PlatformLocation' not found.
  final ui_web.PlatformLocation _platformLocation;
        ^^^^^^^^^^^^^^^^^^^^^^^
/C:/Users/trust/AppData/Local/Pub/Cache/hosted/pub.dev/webview_flutter_web-0.2.2+3/lib/src/http_request_factory.dart:71:21: Error: 'ProgressEvent' isn't a type.
      void Function(ProgressEvent e)? onProgress}) {
                    ^^^^^^^^^^^^^
/C:/Users/trust/AppData/Local/Pub/Cache/hosted/pub.dev/webview_flutter_web-0.2.2+3/lib/src/http_request_factory.dart:72:12: Error: The getter 'HttpRequest' isn't defined for the class 'HttpRequestFactory'.
 - 'HttpRequestFactory' is from 'package:webview_flutter_web/src/http_request_factory.dart' ('/C:/Users/trust/AppData/Local/Pub/Cache/hosted/pub.dev/webview_flutter_web-0.2.2+3/lib/src/http_request_factory.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'HttpRequest'.
    return HttpRequest.request(url,
           ^^^^^^^^^^^
/C:/Users/trust/AppData/Local/Pub/Cache/hosted/pub.dev/webview_flutter_web-0.2.2+3/lib/src/web_webview_controller.dart:41:14: Error: 'IFrameElement' isn't a type.
  final html.IFrameElement iFrame = html.IFrameElement()
             ^^^^^^^^^^^^^
/C:/Users/trust/AppData/Local/Pub/Cache/hosted/pub.dev/webview_flutter_web-0.2.2+3/lib/src/web_webview_controller.dart:41:42: Error: Method not found: 'IFrameElement'.
  final html.IFrameElement iFrame = html.IFrameElement()
                                         ^^^^^^^^^^^^^
/C:/Users/trust/AppData/Local/Pub/Cache/hosted/pub.dev/webview_flutter_web-0.2.2+3/lib/src/web_webview_controller.dart:89:16: Error: 'HttpRequest' isn't a type.
    final html.HttpRequest httpReq =
               ^^^^^^^^^^^
/C:/Users/trust/AppData/Local/Pub/Cache/hosted/pub.dev/webview_flutter_web-0.2.2+3/lib/src/web_webview_controller.dart:118:12: Error: Undefined name 'platformViewRegistry'.
    ui_web.platformViewRegistry.registerViewFactory(
           ^^^^^^^^^^^^^^^^^^^^
/C:/Flutter/packages/flutter_web_plugins/lib/src/navigation/url_strategy.dart:21:28: Error: 'UrlStrategy' isn't a type.
void setUrlStrategy(ui_web.UrlStrategy? strategy) {
                           ^^^^^^^^^^^
/C:/Flutter/packages/flutter_web_plugins/lib/src/navigation/url_strategy.dart:22:10: Error: Setter not found: 'urlStrategy'.
  ui_web.urlStrategy = strategy;
         ^^^^^^^^^^^
/C:/Flutter/packages/flutter_web_plugins/lib/src/navigation/url_strategy.dart:45:3: Error: The superclass, 'ui_web.HashUrlStrategy', has no unnamed constructor that takes no arguments.
  PathUrlStrategy([
  ^^^^^^^^^^^^^^^
/C:/Flutter/packages/flutter_web_plugins/lib/src/navigation/url_strategy.dart:52:16: Error: 'PlatformLocation' isn't a type.
  final ui_web.PlatformLocation _platformLocation;
               ^^^^^^^^^^^^^^^^
/C:/Flutter/packages/flutter_web_plugins/lib/src/plugin_registry.dart:65:12: Error: Method not found: 'setPluginHandler'.
    ui_web.setPluginHandler(handleFrameworkMessage);
           ^^^^^^^^^^^^^^^^
Unhandled exception:
FileSystemException(uri=org-dartlang-untranslatable-uri:dart%3Ahtml; message=StandardFileSystem only supports file:* and data:* URIs)
#0      StandardFileSystem.entityForUri (package:front_end/src/api_prototype/standard_file_system.dart:34:7)
#1      asFileUri (package:vm/kernel_front_end.dart:721:37)
#2      writeDepfile (package:vm/kernel_front_end.dart:861:21)
<asynchronous suspension>
#3      FrontendCompiler.compile (package:frontend_server/frontend_server.dart:669:9)
<asynchronous suspension>
#4      starter (package:frontend_server/starter.dart:102:12)
<asynchronous suspension>
#5      main (file:///C:/b/s/w/ir/x/w/sdk/pkg/frontend_server/bin/frontend_server_starter.dart:13:14)
<asynchronous suspension>

Target kernel_snapshot failed: Exception

FAILURE: Build failed with an exception.

* Where:
Script 'C:\Flutter\packages\flutter_tools\gradle\src\main\groovy\flutter.groovy' line: 1297

**Comment by moluopro** [comment]
Kindly try using the latest version to check if the issue has been resolved.    
Also, running flutter clean before rebuilding the app might help.    
I’ve tested flutter run -d edge on Windows, and it ran fine without any problems.

**Comment by moluopro** [comment]
Sorry for the long delay in replying.
